### ISSUE TITLE
It is not compiled.

### ISSUE THREAD

**Issue by denilly** [SapientHetero/Ethernet#2]
Good morning @SapientHetero, I'm having intermittent connectivity issues on SNMP and HTTP requests. It works for a while, but randomly lose connectivity, ping (ICMP) always responds. I have included server.begin () in the loop in which instability has improved, but connectivity drops remain, but the difference is that connectivity reestablishes itself. Because of this, I tried to use the Ethernet library you modified, but always has an error when compiling. Could help? Thankful!

**Comment by denilly** [comment]
Follow errors while compiling ...

"C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:145:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, expected)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static void EthernetClass::socketClose(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:267:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::CLOSE_WAIT, SnSR::CLOSED, SnSR::FIN_WAIT)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static uint8_t EthernetClass::socketListen(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:288:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::LISTEN)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static void EthernetClass::socketConnect(uint8_t, uint8_t*, uint16_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:308:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::ESTABLISHED)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static void EthernetClass::socketDisconnect(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:327:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::TIME_WAIT, SnSR::CLOSED, SnSR::FIN_WAIT)) { // wait for command to complete, as indicated by Socket n Status Register

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static uint32_t EthernetClass::getWaitTime()':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:755:21: error: 'class W5100Class' has no member named 'getAvgWait'

uint32_t t = W5100.getAvgWait();"

**Comment by denilly** [comment]
Follow errors while compiling ...

"C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:145:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, expected)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static void EthernetClass::socketClose(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:267:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::CLOSE_WAIT, SnSR::CLOSED, SnSR::FIN_WAIT)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static uint8_t EthernetClass::socketListen(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:288:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::LISTEN)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static void EthernetClass::socketConnect(uint8_t, uint8_t*, uint16_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:308:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::ESTABLISHED)) {

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static void EthernetClass::socketDisconnect(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:327:13: error: 'class W5100Class' has no member named 'waitForCmd'

if (!W5100.waitForCmd(s, SnSR::TIME_WAIT, SnSR::CLOSED, SnSR::FIN_WAIT)) { // wait for command to complete, as indicated by Socket n Status Register

         ^~~~~~~~~~
C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp: In static member function 'static uint32_t EthernetClass::getWaitTime()':

C:\Program Files (x86)\Arduino\libraries\Ethernet\src\socket.cpp:755:21: error: 'class W5100Class' has no member named 'getAvgWait'

uint32_t t = W5100.getAvgWait();"

**Comment by SapientHetero** [comment]
Apologies; when I uploaded to GitHub I put the new w5100 files in the main directory instead of the utility directory where they belong. They are now where they belong.

**Comment by denilly** [comment]
Hello. Thanks for the feedback, and you are now experiencing another error in the compilation. Thankful.

Follow...

Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:16:10: fatal error: wdtFunctions.h: No such file or directory
Foram encontradas múltiplas bibliotecas para "EasyWebServer.h"
Usado: /Users/macbook/Documents/Arduino/libraries/EasyWebServer-1.0.0
Foram encontradas múltiplas bibliotecas para "Streaming.h"
Usado: /Users/macbook/Documents/Arduino/libraries/Streaming
Foram encontradas múltiplas bibliotecas para "Ethernet.h"
 #include "wdtFunctions.h"     ////// WARNING! A copy of wdtFunctions had to be put in Ethernet/src directory to make this work. Make sure to update it if the main version ever changes

Usado: /Applications/Arduino.app/Contents/Java/libraries/Ethernet
          ^~~~~~~~~~~~~~~~
Foram encontradas múltiplas bibliotecas para "SPI.h"
compilation terminated.
Usado: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI
Foram encontradas múltiplas bibliotecas para "Agentuino.h"
Usado: /Users/macbook/Documents/Arduino/libraries/Agentuino
Foram encontradas múltiplas bibliotecas para "DHT.h"
Usado: /Users/macbook/Documents/Arduino/libraries/DHT
exit status 1
Erro compilando para a placa Arduino/Genuino Uno
