### ISSUE TITLE
Watchdog Timer must be included or commented out to compile

### ISSUE THREAD

**Issue by denilly** [SapientHetero/Ethernet#3]
Apologies; when I uploaded to GitHub I put the new w5100 files in the main directory instead of the utility directory where they belong. They are now where they belong.

_Originally posted by @SapientHetero in https://github.com/SapientHetero/Ethernet/issues/2#issuecomment-541329431_

Hello. Thanks for the feedback, and you are now experiencing another error in the compilation. Thankful.

Follow...

Applications/Arduino.app/Contents/Java/libraries/Ethernet/src/utility/w5100.cpp:16:10: fatal error: wdtFunctions.h: No such file or directory
Foram encontradas múltiplas bibliotecas para "EasyWebServer.h"
Usado: /Users/macbook/Documents/Arduino/libraries/EasyWebServer-1.0.0
Foram encontradas múltiplas bibliotecas para "Streaming.h"
Usado: /Users/macbook/Documents/Arduino/libraries/Streaming
Foram encontradas múltiplas bibliotecas para "Ethernet.h"
#include "wdtFunctions.h" ////// WARNING! A copy of wdtFunctions had to be put in Ethernet/src directory to make this work. Make sure to update it if the main version ever changes

Usado: /Applications/Arduino.app/Contents/Java/libraries/Ethernet
^~~~~~~~~~~~~~~~
Foram encontradas múltiplas bibliotecas para "SPI.h"
compilation terminated.
Usado: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI
Foram encontradas múltiplas bibliotecas para "Agentuino.h"
Usado: /Users/macbook/Documents/Arduino/libraries/Agentuino
Foram encontradas múltiplas bibliotecas para "DHT.h"
Usado: /Users/macbook/Documents/Arduino/libraries/DHT
exit status 1
Erro compilando para a placa Arduino/Genuino Uno

**Comment by SapientHetero** [comment]
wdtFunctions.h refers to a watchdog timer, available at [https://github.com/SapientHetero/Watchdog-Timer-for-ATSAMD51J19A](url). If you prefer not to use it, comment out references to wdtFunctions.h and any function calls beginning with wdt. I'll modify the library in the future to use a symbol that can be used to do this automatically but don't have time today.

**Comment by SapientHetero** [comment]
Added USE_WDT flag that by default disables use of watchdog timer.
