### ISSUE TITLE
ESP32 + W5500 Lite

### ISSUE THREAD

**Issue by ale-trevizoli** [SapientHetero/Ethernet#4]
Hi. I'm trying to use your library in my project, because I'm having issues with corrupt web pages, but if I use this, I receive message that ethernet module not found on webserver sample, if I change SPI speed for 14MHZ, it can find module but webserver not answer when I try to connect on browser.

https://wiznetmuseum.com/portfolio-items/bitconn-w5500-module/

**Comment by SapientHetero** [comment]
Are you calling manageSockets() each time your webserver runs? Browsers
will open as many as 6 concurrent connections if your pages load other
resources (eg, .css files, scripts, images, etc) so I generally specify 6
listeners in my manageSockets() calls.

If that's not the problem, post your code and I'll see if I can help.

**Comment by ale-trevizoli** [comment]
Thank you for your answer. 
How can I change Webserver Sample to use manageSockets?
https://github.com/SapientHetero/Ethernet/blob/master/examples/WebServer/WebServer.ino

And how can I make library compatible with W5100 & W5500 chips?
Because same code I run with both chips, you think is possible?
Thanks a lot!

**Comment by SapientHetero** [comment]
Add manageSockets() call at the beginning of the loop() function in the
example. Read README.rtf in the repository for details.

In theory, the library should work for W5500 and W5100, but I don't have a
W5100 board to test it. For some reason Wiznet changed addresses of some
W5500 registers that were also present in the W5100. I commented on these
in w5100.h and also in readme.rtf.

If you find problems please let me know.

Thanks.

**Comment by SapientHetero** [comment]
I just built the Webserver example using manageSockets() but it required a bit of cleanup of external references in my code that you won't want or need. I'll look at that part tomorrow and try to post an updated version you can build more easily. But other than that, all I had to do is add one line of code, as shown below.

`void loop() {
  // listen for incoming clients
  Ethernet.manageSockets(&server, 6, 7);    // 6 listeners, reserve socket 7 for dedicated purpose.
  EthernetClient client = server.available();`

The cleanup involves #ifdef'ing the wdtClear() calls to the watchdog timer, which is also available in github if you want to use it to restart your system if it hangs up anywhere.

**Comment by SapientHetero** [comment]
Added manageSockets() call to Webserver.ino example and tested with Wiznet W500 shield.
